### ISSUE TITLE
Jpeg Support/simple xml

### ISSUE THREAD

**Issue by adisoftbn** [databank/aws-lambda-php-template#1]
The binary doesn't have jpeg and simple xml support. If I compile by my own I have a conflict with libssl.so in the lambda instance.

**Comment by adrianpraja** [comment]
Hi Adrian,

I'll have a look into it and push another binary with jpeg and simplexml support if possible

**Comment by adrianpraja** [comment]
I've uploaded another binary with SimpleXML support
Also enabled jpeg support 

PS: no checks were made to ensure these additions actually work :)

**Comment by adisoftbn** [comment]
Hello :D You're awesome !!! :) This will help many ! Cheers!
