### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by postme** [databank/aws-lambda-php-template#2]
Hi there,
first of all thank you for putting this on Github, there's very few examples that deal with running php on Lambda, yours is about the only one so far. However I can't get it to run so I'm hoping for some pointers in getting this working.

I have downloaded the zip file, unzipped it and made a new zip file named Test.zip that contains php, index.js and index.php

I have set up a Lambda function with the following parameters
Name: MyDemo
Description: A starter AWS Lambda function.
Runtime: NodeJS
Handler: index.handler
RoleL lambda_basic_execution
Memory (MB): 128
Timeout (s): 3

The Test output of Lambda is:
START RequestId: 13a0f4bd-3c00-11e5-bb24-63fd3fcf04b4
END RequestId: 13a0f4bd-3c00-11e5-bb24-63fd3fcf04b4
REPORT RequestId: 13a0f4bd-3c00-11e5-bb24-63fd3fcf04b4  Duration: 243.17 ms Billed Duration: 300 ms     Memory Size: 128 MB Max Memory Used: 10 MB  
Process exited before completing request

The output of CloudWatch Logs:
START RequestId: 13a0f4bd-3c00-11e5-bb24-63fd3fcf04b4 
 events.js:72 
 throw er; // Unhandled 'error' event 
 ^ 
Error: write EPIPE 
 at errnoException (net.js:905:11) 
 at Object.afterWrite (net.js:721:19) 
END RequestId: 13a0f4bd-3c00-11e5-bb24-63fd3fcf04b4 
REPORT RequestId: 13a0f4bd-3c00-11e5-bb24-63fd3fcf04b4  Duration: 243.17 ms Billed Duration: 300 ms Memory Size: 128 MB Max Memory Used: 10 MB  
Process exited before completing request

I have also run index.js with console.log statements and all those console.log statements generate correct output until the end of the function.

Any idea why it's not working?

**Comment by postme** [comment]
Sorry, found the issue, I was zipping it on Windows and then found a remark in the Lambda forum that it needss to be zipped on a Linux platform. I did that and now its working fine.

**Comment by adrianpraja** [comment]
I had no idea about lambda issue with windows zipped files
I'll make some tests myself and update the readme 

Thanks
