### ISSUE TITLE
uploading zip file will be rejected because of the php binary file.

### ISSUE THREAD

**Issue by leftdevel** [databank/aws-lambda-php-template#3]
Hi There. This might not be an issue with your project, sorry beforehand if this is a silly question.

I'm not able to upload your project (zipped), when creating a new lambda function. I debugged the issue and if I remove the php binary file, then aws will let me upload the zip file. But the strange thing is that an error message box is displayed but has no error message, so I have no clue whatsoever why the php binary is triggering the issue. Btw, I got rid of the .git project dir, so it doesn't seems to be a file size issue.

In order to exclude compatibility issues, I cloned your repo in a ec2 linux instance and ran the compile.sh script, I replaced the php binary file with the newly generated one, but I still get the same weird error.

Have you run into this before, any thoughts? Thanks!

**Comment by adrianpraja** [comment]
Hi,

It probably has something to do with the way you are pack it.

i just did a new checkout and deploy it using [aws-lambda npm](https://www.npmjs.com/package/aws-lambda) 

than ran it:
START RequestId: 594db8b4-ec51-11e5-b9c0-f3c381fcad7a Version: $LATEST
2016-03-17T15:03:03.990Z    594db8b4-ec51-11e5-b9c0-f3c381fcad7a    array(3) {
  ["key3"]=>
  string(6) "value3"
  ["key2"]=>
  string(6) "value2"
  ["key1"]=>
  string(6) "value1"
}
Array
(
    [0] => Core
    [1] => date
    [2] => ereg
    [3] => libxml
    [4] => openssl
    [5] => pcre
    [6] => curl
    [7] => standard
    [8] => gd
    [9] => hash
    [10] => json
    [11] => mbstring
    [12] => SPL
    [13] => Phar
    [14] => Reflection
    [15] => SimpleXML
    [16] => sockets
    [17] => exif
    [18] => xml
    [19] => mhash
)

2016-03-17T15:03:03.991Z    594db8b4-ec51-11e5-b9c0-f3c381fcad7a    child process exited with code 0
END RequestId: 594db8b4-ec51-11e5-b9c0-f3c381fcad7a
REPORT RequestId: 594db8b4-ec51-11e5-b9c0-f3c381fcad7a  Duration: 17.45 ms  Billed Duration: 100 ms     Memory Size: 512 MB Max Memory Used: 11 MB

**Comment by leftdevel** [comment]
Thanks! I'll check that out.
