### ISSUE TITLE
ERROR`	Uncaught Exception related to EPIPE

### ISSUE THREAD

**Issue by Tekrajs** [databank/aws-lambda-php-template#7]
Nowadays this library gives me the following error

` ERROR	Uncaught Exception	
{
    "errorType": "Error",
    "errorMessage": "write EPIPE",
    "code": "EPIPE",
    "errno": "EPIPE",
    "syscall": "write",
    "stack": [
        "Error: write EPIPE",
        "    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)"
    ]
}`

How to solve this issue ?

**Comment by adrianpraja** [comment]
Hi, Im sorry this repository is no longer maintained, 

now you have AWS Lambda custom runtimes 

The error I'm assuming is due to no disk space available
